### ISSUE TITLE
Battery isn't reporting percent correctly!

### ISSUE THREAD

**Issue by croxis** [SZinedine/auzia-conky#1]
![image](https://user-images.githubusercontent.com/121591/132791532-207f9fc1-1dc7-4b6e-af06-bb768e005303.png)
 I only have one battery

**Comment by R0X0RE0** [comment]
Yeah I noticed it's going with half of what I have on my battery level. Kinda bothersome, to be honest. I tried looking through the Lua scripts for a battery percentage that seemed like it was being divided in half, but I didn't really see anything.

**Comment by R0X0RE0** [comment]
Oh, I found it, in the abstract.lua file (lines 380-384)
`
battery_percent = function() 
                local b0 = tonumber(battery1_percent())
                local b1 = tonumber(battery2_percent())
                return math.floor((b0 + b1)/2)
            end
`
In `return math.floor((b0 + b1)/2)`, remove the /2
